import assert from 'node:assert/strict';import {test} from 'node:test';import {createRequire} from 'node:module';import {readFileSync,mkdirSync} from 'node:fs';import {join,resolve} from 'node:path';import {createServer} from 'vite';import {chromium} from '@playwright/test';
const require=createRequire(import.meta.url);
const fixture=`import React from 'react';import {createRoot} from 'react-dom/client';import {ThemeProvider} from '/src/components/ThemeProvider.tsx';import {Card} from '/src/components/Card.tsx';import {Button} from '/src/components/Button.tsx';import {LinkButton} from '/src/components/Content.tsx';import {Badge} from '/src/components/Badge.tsx';import {ButtonGroup} from '/src/components/ButtonGroup.tsx';import {Input} from '/src/components/forms/Input.tsx';import {Toggle} from '/src/components/forms/Toggle.tsx';import {Slider} from '/src/components/Slider.tsx';import {Tabs,Progress} from '/src/components/Widgets.tsx';import {PROJECTION_THEME,COASTAL_DAY_THEME,PROJECTION_FLAT_THEME,PROJECTION_LIGHT_FLAT_THEME as COASTAL_DAY_FLAT_THEME} from '/src/foundations.ts';
function Example({theme,id}){const[v,setV]=React.useState('a'),[checked,setChecked]=React.useState(true),[amount,setAmount]=React.useState(55);return React.createElement(ThemeProvider,{theme,style:{background:theme.bg,padding:24}},React.createElement('section',{'data-case':id,style:{display:'grid',gap:16}},React.createElement(Card,{className:'card'},'Panel'),React.createElement(Input,{label:'Field',defaultValue:'Readable value'}),React.createElement(Button,{variant:'primary',className:'action'},'Action'),React.createElement(Button,{variant:'primary',appearance:'solid',className:'solid'},'Solid action'),React.createElement(LinkButton,{href:'#details',variant:'primary',appearance:'gradient',className:'gradient-link'},'Read details'),React.createElement(LinkButton,{href:'#details',variant:'primary',className:'solid-link'},'Solid link'),React.createElement(Badge,{filled:true,className:'badge'},'Selected'),React.createElement(ButtonGroup,{value:v,onChange:setV,'aria-label':'Modes',options:[{value:'a',label:'First'},{value:'b',label:'Next'}]}),React.createElement(Toggle,{checked,onChange:setChecked,label:'Enabled'}),React.createElement(Slider,{value:amount,onChange:setAmount,label:'Amount'}),React.createElement(Progress,{value:amount,label:'Completion'}),React.createElement(Tabs,{label:'Views',items:[{value:'a',label:'Overview',content:'Content'},{value:'b',label:'Details',content:'More'}]})));}
createRoot(document.getElementById('root')).render(React.createElement(React.Fragment,null,...[[PROJECTION_THEME,'dark'],[COASTAL_DAY_THEME,'light'],[PROJECTION_FLAT_THEME,'flat-dark'],[COASTAL_DAY_FLAT_THEME,'flat-light']].map(([theme,id])=>React.createElement(Example,{key:id,theme,id}))));`;
test('paired gradients reach modern panels and controls while flat remains solid and readable',async()=>{
const server=await createServer({configFile:false,plugins:[{name:'gradient-fixture',resolveId(id){if(id==='virtual:gradient')return '\0virtual:gradient'},load(id){if(id==='\0virtual:gradient')return fixture}}],root:resolve('.'),server:{host:'127.0.0.1',port:0}});let browser;
try{await server.listen();browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:768,height:1250}});await page.goto(`http://127.0.0.1:${server.httpServer.address().port}`);await page.setContent('<link rel="stylesheet" href="/src/tokens/scoped.css"><style>body{margin:0}#root{display:grid;grid-template-columns:repeat(2,minmax(0,1fr))}*{box-sizing:border-box}</style><main id="root"></main>');await page.addScriptTag({type:'module',url:'/@id/__x00__virtual:gradient'});await page.locator('[data-case=flat-light]').waitFor();await page.emulateMedia({reducedMotion:'reduce'});
for(const id of ['dark','light','flat-dark','flat-light']){const area=page.locator(`[data-case=${id}]`);const modern=!id.startsWith('flat');for(const selector of ['.action','.gradient-link','.card','.ui-field','.badge','[role=radio][aria-checked=true]','.ui-toggle-track','[role=tab][aria-selected=true]']){const image=await area.locator(selector).evaluate(n=>getComputedStyle(n).backgroundImage);assert.equal(image.includes('linear-gradient'),modern,`${id} ${selector}`);}assert.equal(await area.locator('.solid').evaluate(n=>getComputedStyle(n).backgroundImage),'none');assert.equal(await area.locator('.solid-link').evaluate(n=>getComputedStyle(n).backgroundImage),'none','Existing link buttons retain solid defaults');assert.equal(await area.locator('.gradient-link').getAttribute('href'),'#details');assert.equal(await area.locator('.ui-slider-track').evaluate(n=>getComputedStyle(n).getPropertyValue('--ui-accent-end').trim()),modern?(id==='dark'?'#A1F55B':'#369FFF'):(id==='flat-dark'?'#C9F53A':'#00C8FF'));}
await page.addScriptTag({content:readFileSync(require.resolve('axe-core/axe.min.js'),'utf8')});for(const width of [390,768]){await page.setViewportSize({width,height:1250});const issues=await page.evaluate(async()=>(await window.axe.run(document.getElementById('root'),{runOnly:['color-contrast']})).violations);assert.deepEqual(issues.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)})),[]);if(process.env.PROJECTION_MATERIAL_EVIDENCE_DIR){mkdirSync(process.env.PROJECTION_MATERIAL_EVIDENCE_DIR,{recursive:true});await page.screenshot({path:join(process.env.PROJECTION_MATERIAL_EVIDENCE_DIR,`gradients-${width}.png`),fullPage:true});}}
await page.emulateMedia({forcedColors:'active'});assert.equal(await page.locator('[data-case=dark] .ui-field').evaluate(n=>getComputedStyle(n).backgroundImage),'none');
}finally{await browser?.close();await server.close();}});
