import { previewTheme, usePreviewTheme } from '../.storybook/PreviewTheme'
import { useState } from 'react'
import type { Meta, StoryObj } from '@storybook/react'
import { Badge, Button, COASTAL_DAY_FLAT_THEME, FERNWOOD_FLAT_THEME, PROJECTION_FLAT_THEME, Card, GradientBackground, GradientText, Surface, THEME_PRESETS, ThemeProvider } from '@hannasage/projection-ui/core'
const meta: Meta = { title: 'Foundations/Themes', parameters: { layout: 'fullscreen' } }
export default meta
export const Presets: StoryObj = { render: () => <main className="component-gallery"><h1>Theme presets</h1><p>Every preset supplies the same theme roles.</p><div className="theme-presets">{Object.entries(THEME_PRESETS).map(([id, theme]) => <ThemeProvider key={id} theme={theme}><h2 style={{marginTop:0}}>{theme.name}</h2><p>{theme.mode === 'light' ? 'Light' : 'Dark'} theme</p><Card material="glass" edgeLight><Badge>Preview</Badge><p>Clear type and a quiet material.</p><Button appearance="gradient" onClick={event => { event.currentTarget.textContent = 'Selected' }}>Select preset</Button></Card></ThemeProvider>)}</div></main> }
export const Materials: StoryObj = { render: () => <main className="component-gallery"><h1>Surface materials</h1><div className="theme-presets">{Object.entries(THEME_PRESETS).filter(([id]) => ['coastal-day','projection'].includes(id)).map(([id,theme]) => <ThemeProvider key={id} theme={theme}><GradientBackground variant="atmosphere" style={{padding:24}}><Surface material="glass" edgeLight underglow style={{padding:24}}><h2 style={{marginTop:0}}>Glass with light</h2><p>Blur belongs to the background. Content stays clear.</p></Surface></GradientBackground></ThemeProvider>)}</div></main> }
export const Gradients: StoryObj = { render: (_, context) => <main className="component-gallery"><h1>Gradient backgrounds</h1><ThemeProvider theme={previewTheme(context.globals.theme)}><div className="theme-presets">{(['wash','spotlight','horizon','atmosphere'] as const).map(variant => <GradientBackground key={variant} variant={variant} style={{padding:24,minHeight:180}}><h2 style={{marginTop:0}}>{variant}</h2><GradientText>Projection UI</GradientText></GradientBackground>)}</div></ThemeProvider></main> }
export const Typography: StoryObj = { render: (_, context) => <main className="component-gallery"><h1>Typography</h1><ThemeProvider theme={previewTheme(context.globals.theme)} style={{padding:24}}><h2 style={{fontFamily:'var(--ui-font-display)'}}>Syne · A clear point of view</h2><p style={{fontFamily:'var(--ui-font-body)',maxWidth:'68ch'}}>IBM Plex Sans carries reading text. Compact headings keep the page calm. Give related controls a close rhythm, then leave space before the next subject.</p><pre style={{fontFamily:'var(--ui-font-mono)',whiteSpace:'pre-wrap'}}>IBM Plex Mono · --ui-font-mono</pre></ThemeProvider></main> }

export const Flat: StoryObj = { render: () => <main className="component-gallery"><h1>Flat core themes</h1><p>Solid surfaces for the core pair, with the original Fernwood palette still available.</p><div className="theme-presets">{[COASTAL_DAY_FLAT_THEME,PROJECTION_FLAT_THEME,FERNWOOD_FLAT_THEME].map(theme => <ThemeProvider key={theme.name} theme={theme}><h2 style={{marginTop:0}}>{theme.name}</h2><Card material="glass" edgeLight underglow><p>Flat appearance keeps surfaces solid and removes decorative light.</p><Button appearance="gradient" onClick={event => {event.currentTarget.textContent = 'Selected'}}>Select flat theme</Button></Card></ThemeProvider>)}</div></main> }

function PresetExplorer() {
  const initialTheme = usePreviewTheme()
  const [id,setId] = useState<keyof typeof THEME_PRESETS>(() => initialTheme.mode === 'light' ? 'coastal-day' : 'projection')
  const theme = THEME_PRESETS[id]
  return <main className="component-gallery"><h1>Explore a theme</h1><label htmlFor="theme-preset">Theme preset</label><select id="theme-preset" value={id} onChange={event => setId(event.currentTarget.value as keyof typeof THEME_PRESETS)} style={{display:'block',margin:'12px 0 24px',padding:12,color:'var(--preview-text)',background:'var(--preview-bg)',border:'1px solid var(--preview-border)'}}>{Object.entries(THEME_PRESETS).map(([key,value]) => <option key={key} value={key}>{value.name}</option>)}</select><ThemeProvider theme={theme} style={{padding:24,background:theme.bg,color:theme.text}}><GradientBackground variant="spotlight" style={{padding:24}}><Card material="glass" edgeLight underglow><h2 style={{marginTop:0}}>{theme.name}</h2><p>The selected palette updates these real components.</p><Badge>Live preview</Badge><Button appearance="gradient" onClick={event => {event.currentTarget.textContent='Preview selected'}}>Try the accent</Button></Card></GradientBackground></ThemeProvider></main>
}
export const Explorer: StoryObj = { render: () => <PresetExplorer /> }
